name: Go

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.PAT}}
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build Windows x64
      run: GOOS=windows GOARCH=amd64 go build
    # - name: Zip
    #   run: zip release * .pullignore
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        makeLatest: true
        tag: ${{ github.ref_name }}
        artifacts: "adbgo.exe"
        token: ${{ secrets.PAT }}
