name: Go

on:
  push:
    branches: [ master ]
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{secrets.PAT}}
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: GOOS=windows GOARCH=amd64 go build
    - name: Zip
      run: zip release *
    - name: Debug ncipollo/release-action
      env: 
        XXX: ${{ github.ref_name }}
      run: |
        echo $GITHUB_REF_NAME
        echo $XXX
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        tag: ${{ github.ref_name }}
        artifacts: "release.zip"
        token: ${{secrets.PAT}}
